python main.py recognize -f data/tests/1-forrest-king-monkey-house-please.wav
python main.py recognize -f data/tests/2-king-please-sea-validate-house.wav
python main.py recognize -f data/tests/3-lion-forrest-sea-house-bacon.wav
python main.py recognize -f data/tests/4-sea-lion-please-validate-application.wav
python main.py recognize -f data/tests/5-lion-application-forrest-sea-house.wav
python main.py recognize -f data/tests/6-bacon-forrest-application-king-house.wav
python main.py recognize -f data/tests/7-forrest-king-lion-monkey-sea.wav
python main.py recognize -f data/tests/8-monkey-please-validate-bacon-application.wav
python main.py recognize -f data/tests/9-bacon-monkey-application-king-please.wav
python main.py recognize -f data/tests/10-application-king-monkey-validate-lion.wav
python main.py recognize -f data/tests/11-bacon-validate-house-forrest-please.wav
python main.py recognize -f data/tests/12-lion-bacon-sea-forrest-monkey.wav
python main.py recognize -f data/tests/13-validate-house-sea-monkey-king.wav
python main.py recognize -f data/tests/14-sea-lion-bacon-application-please.wav
python main.py recognize -f data/tests/15-king-house-sea-validate-lion.wav
python main.py recognize -f data/tests/16-king-monkey-application-forrest-bacon.wav
python main.py recognize -f data/tests/17-please-validate-application-house-bacon.wav
python main.py recognize -f data/tests/18-forrest-application-monkey-lion-validate.wav
python main.py recognize -f data/tests/19-sea-lion-forrest-house-please.wav
python main.py recognize -f data/tests/20-please-validate-monkey-bacon-king.wav